<?php

namespace foot5x5\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use foot5x5\UserBundle\Entity\User;

/**
 * RolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesRepository extends EntityRepository
{
	public function assignRole(User $user, Community $community, string $role) {
		$userRole = new Roles();
		
		
		
	}
}
