<?php

namespace foot5x5\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use foot5x5\MainBundle\Entity\Community;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
	public function listAllByCommunity(Community $community) {
	    $qb = $this->createQueryBuilder('trn')
	       ->Join('trn.giver', 'giv')
	       ->Join('trn.receiver', 'rec')
	       ->where('giv.community = :community')
	       ->andWhere('rec.community = :community')
	       ->setParameter('community', $community)
    	   ->orderBy('trn.date', 'DESC');

        return $qb->getQuery()->getResult();
    }

	public function listLast($communityId, $nbTransactions)
	{
		$qb = $this->createQueryBuilder('trn')
			->Join('trn.giver', 'giv')
			->addSelect('giv')
			->Join('trn.receiver', 'rec')
			->addSelect('rec')
			->orderBy('trn.date', 'DESC')
			->addOrderBy('giv.name', 'ASC')
			->addOrderBy('rec.name', 'ASC')
			->setMaxResults($nbTransactions);
		
		return $qb->getQuery()->getResult();
    }
}
