<?php

namespace foot5x5\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
	public function listAllByTrimester($year, $trimester) {
    	$qb = $this->createQueryBuilder('trn');
    	// $qb->where('res.year = :year')
    	// 	->setParameter('year', $year)
    	// 	->andWhere('res.trimester = :trim')
    	// 	->setParameter('trim', $trimester)
    	$qb->orderBy('trn.date', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function listLast($nbTransactions) {
    	$qb = $this->createQueryBuilder('trn')
            ->Join('trn.giver', 'giv')
            ->addSelect('giv')
            ->Join('trn.receiver', 'rec')
            ->addSelect('rec');
    	$qb->orderBy('trn.date', 'DESC')
    		->addOrderBy('giv.name', 'ASC')
            ->addOrderBy('rec.name', 'ASC')
            ->setMaxResults($nbTransactions);

        return $qb->getQuery()->getResult();
    }
}
