<?php

namespace foot5x5\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByCommunity($communityId)
	{
		$qb = $this->createQueryBuilder('usr')
			->leftJoin('usr.userRoles', 'roles')
			->where('roles.community = :cmnId')
			->setParameter('cmnId', $communityId)
			->addOrderBy('usr.username', 'ASC');
		
		return $qb->getQuery()->getResult();
	}
}
