foot5x5_main_homepage:
    path:     /
    defaults:
        _controller: foot5x5MainBundle:Main:index

login:
    path:     /login
    defaults:
        _controller: foot5x5MainBundle:Main:login

register:
    path:     /register
    defaults:
        _controller: foot5x5UserBundle:Registration:register

register_check:
    path:     /register_check

welcome:
    path:     /welcome
    defaults:
        _controller: foot5x5MainBundle:Main:welcome

create_community:
    path:     /community/create
    defaults:
        _controller: foot5x5MainBundle:Community:create

select_community:
    path:     /community/select/{id}
    defaults:
        _controller: foot5x5MainBundle:Community:select

community_home:
    path:     /community/home
    defaults:
        _controller: foot5x5MainBundle:Community:home

myprofile:
    path:     /profile
    defaults:
        _controller: foot5x5MainBundle:Main:profile

edit_pwd:
    path:     /profile/edit_pwd
    defaults:
        _controller: foot5x5MainBundle:Main:editPwd

results:
    path:     /results
    defaults:
        _controller: foot5x5MainBundle:Main:results

standing:
    path:     /standing/{id}
    defaults:
        _controller: foot5x5MainBundle:Main:standing

standings:
    path:     /standings
    defaults:
        _controller: foot5x5MainBundle:Main:standings

players:
    path:     /players
    defaults:
        _controller: foot5x5MainBundle:Main:players

notes:
    path:     /notes
    defaults:
        _controller: foot5x5MainBundle:Main:notes

edit_note:
    path:     /note/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Main:editNote

delete_note:
    path:     /note/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Main:deleteNote

random_draw:
    path:     /random
    defaults:
        _controller: foot5x5MainBundle:Main:randomDraw

finances:
    path:     /finances
    defaults:
        _controller: foot5x5MainBundle:Main:finances

admin_home:
    path:     /admin
    defaults:
        _controller: foot5x5MainBundle:Admin:index

add_match:
    path:     /admin/match/add
    defaults:
        _controller: foot5x5MainBundle:Admin:addMatch

edit_match:
    path:     /admin/match/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Admin:editMatch

delete_match:
    path:     /admin/match/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deleteMatch

calc_standing:
    path:     /admin/standing/{id}/calc
    defaults:
        _controller: foot5x5MainBundle:Admin:calcStanding

delete_standing:
    path:     /admin/standing/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deleteStanding

add_player:
    path:     /admin/player/add
    defaults:
        _controller: foot5x5MainBundle:Admin:addPlayer

edit_player:
    path:     /admin/player/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Admin:editPlayer

delete_player:
    path:     /admin/player/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deletePlayer

update_player_balance:
    path:     /admin/player/{id}/{operation}
    defaults:
        _controller: foot5x5MainBundle:Admin:updatePlayerBalance

add_user:
    path:     /admin/user/add
    defaults:
        _controller: foot5x5MainBundle:Admin:addUser

edit_user:
    path:     /admin/user/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Admin:editUser

delete_user:
    path:     /admin/user/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deleteUser

add_transaction:
    path:     /admin/transaction/add
    defaults:
        _controller: foot5x5MainBundle:Admin:addTransaction

edit_transaction:
    path:     /admin/transaction/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Admin:editTransaction

delete_transaction:
    path:     /admin/transaction/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deleteTransaction
