foot5x5_main_homepage:
    path:     /
    defaults:
        _controller: foot5x5MainBundle:Main:index

home:
    path:     /home
    defaults:
        _controller: foot5x5MainBundle:Main:home

register:
    path:     /register
    defaults:
        _controller: foot5x5UserBundle:Registration:register

register_check:
    path:     /register_check

welcome:
    path:     /welcome
    defaults:
        _controller: foot5x5MainBundle:Main:welcome

create_community:
    path:     /community/create
    defaults:
        _controller: foot5x5MainBundle:Community:create

join_community:
    path:     /community/join
    defaults:
        _controller: foot5x5MainBundle:Community:join

select_community:
    path:     /community/select/{id}
    defaults:
        _controller: foot5x5MainBundle:Community:select

community_home:
    path:     /community/home
    defaults:
        _controller: foot5x5MainBundle:Community:home

myprofile:
    path:     /profile
    defaults:
        _controller: foot5x5MainBundle:Main:profile

edit_pwd:
    path:     /profile/edit_pwd
    defaults:
        _controller: foot5x5MainBundle:Main:editPwd

results:
    path:     /community/results
    defaults:
        _controller: foot5x5MainBundle:Community:results

standing:
    path:     /community/standing/{id}
    defaults:
        _controller: foot5x5MainBundle:Main:standing

standings:
    path:     /community/standings
    defaults:
        _controller: foot5x5MainBundle:Community:standings

players:
    path:     /community/players
    defaults:
        _controller: foot5x5MainBundle:Community:players

notes:
    path:     /community/notes
    defaults:
        _controller: foot5x5MainBundle:Community:notes

edit_note:
    path:     /community/note/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Community:editNote

delete_note:
    path:     /community/note/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Community:deleteNote

random_draw:
    path:     /community/random
    defaults:
        _controller: foot5x5MainBundle:Community:randomDraw

finances:
    path:     /community/finances
    defaults:
        _controller: foot5x5MainBundle:Community:finances

admin_home:
    path:     /admin
    defaults:
        _controller: foot5x5MainBundle:Admin:index

add_match:
    path:     /admin/match/add
    defaults:
        _controller: foot5x5MainBundle:Admin:addMatch

edit_match:
    path:     /admin/match/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Admin:editMatch

delete_match:
    path:     /admin/match/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deleteMatch

calc_standing:
    path:     /admin/standing/{id}/calc
    defaults:
        _controller: foot5x5MainBundle:Admin:calcStanding

delete_standing:
    path:     /admin/standing/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deleteStanding

add_player:
    path:     /admin/player/add
    defaults:
        _controller: foot5x5MainBundle:Admin:addPlayer

edit_player:
    path:     /admin/player/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Admin:editPlayer

delete_player:
    path:     /admin/player/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deletePlayer

update_player_balance:
    path:     /admin/player/{id}/{operation}
    defaults:
        _controller: foot5x5MainBundle:Admin:updatePlayerBalance

# add_user:
#    path:     /admin/user/add
#    defaults:
#        _controller: foot5x5MainBundle:Admin:addUser

# edit_user:
#    path:     /admin/user/{id}/edit
#    defaults:
#        _controller: foot5x5MainBundle:Admin:editUser

edit_user_role:
    path:     /admin/user/{id}/edit_role
    defaults:
        _controller: foot5x5MainBundle:Admin:editUserRole

# delete_user:
#    path:     /admin/user/{id}/delete
#    defaults:
#        _controller: foot5x5MainBundle:Admin:deleteUser
        
delete_user_role:
    path:     /admin/user/{id}/delete_user_role
    defaults:
        _controller: foot5x5MainBundle:Admin:deleteUserRole

add_transaction:
    path:     /admin/transaction/add
    defaults:
        _controller: foot5x5MainBundle:Admin:addTransaction

edit_transaction:
    path:     /admin/transaction/{id}/edit
    defaults:
        _controller: foot5x5MainBundle:Admin:editTransaction

delete_transaction:
    path:     /admin/transaction/{id}/delete
    defaults:
        _controller: foot5x5MainBundle:Admin:deleteTransaction
